name: "Newman Tests"
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: postman/newman
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run API Tests
      run: newman run "RestfulBookerBVT.postman_collection.json" -e Production.postman_environment.json
